name = "proto-backend"
main = "server/index.ts"
compatibility_date = "2025-01-28"
compatibility_flags = [ "nodejs_compat" ]

[vars]
SUPABASE_URL = "https://mrkxepxtcsxyimlnosgm.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_HjrrnOsAmZB45Q1gtmKa5Q_mEVQVhTW"
